FROM robbyjo/ubuntu-mkl:18.04-2019.1

# System packages
RUN apt-get update && \
    apt-get install -y curl git wget bzip2 libgoogle-perftools-dev graphviz build-essential g++ python3 cmake python3-pip && \
    rm -rf /var/lib/apt/lists/* &&\
    pip3 install --no-cache-dir torch transformers onnxruntime

# install golang
RUN wget --no-check-certificate -qO- https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz | \
    tar -xz -C /usr/local && \
    mkdir /root/gopath && \
    mkdir /root/gopath/bin && \
    mkdir /root/gopath/src
ENV GOROOT=/usr/local/go GOPATH=/root/gopath
ENV PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
RUN go get -u github.com/google/pprof

# add test scripts
RUN mkdir -p /workspace
WORKDIR /workspace
COPY ./tools/build_and_run_unittests.sh /workspace/
