FROM nvidia/cuda:9.0-devel-ubuntu16.04

# System packages
RUN apt-get update && \
    apt-get install -y curl git wget bzip2 build-essential g++ && rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV PATH=/opt/miniconda3/bin:${PATH} CONDA_PREFIX=/opt/miniconda3
RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -p /opt/miniconda3 -b && \
    rm Miniconda3-latest-Linux-x86_64.sh && \
    conda update -y conda && \
    conda install pytorch cudatoolkit=9.0 -c pytorch && \
    conda install curl conda-verify conda-build mkl-include cmake -c anaconda && \
    conda install git git-lfs -c conda-forge  && \
    conda clean -afy
WORKDIR /workspace
