FROM IMAGE_BASE

RUN apt-get update && \
    apt-get install -y curl git wget bzip2 build-essential ninja-build g++ && rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/miniconda3/bin:${PATH} CONDA_PREFIX=/opt/miniconda3
RUN curl -LO https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh && \
    bash Miniconda3-py37_4.8.3-Linux-x86_64.sh -p /opt/miniconda3 -b && \
    rm Miniconda3-py37_4.8.3-Linux-x86_64.sh && \
    conda update -y conda && \
    conda install pytorch=PYTORCH_VERSION cudatoolkit=CUDA_VERSION -c pytorch && \
    conda install curl conda-verify conda-build mkl-include cmake -c anaconda && \
    conda install git git-lfs docopt -c conda-forge  && \
    pip install OpenNMT-py==1.1.0 && \
    pip install onnxruntime-gpu==1.3.0 && \
    conda clean -afy

# build turbo
RUN mkdir -p /src && cd /src && git clone https://github.com/Tencent/TurboTransformers.git --recursive && cd ./TurboTransformers && \
    sh ./tools/build_and_run_unittests.sh $PWD -DWITH_GPU=ON

WORKDIR /workspace
