# Build ONNX Runtime for benchmark
FROM continuumio/anaconda3

RUN apt-get update && apt-get install -y gfortran build-essential
RUN /opt/conda/bin/conda install cmake curl git numpy -c anaconda

# Try to install deps by anaconda
# NOTE:  1. MKL is installed with pytorch.
#           turbo-transformers will use the same MKL from pytorch

RUN   /opt/conda/bin/conda install pytorch==1.3.1 cpuonly -c pytorch && \
    pip install OpenNMT-py==1.1.1 && \
    /opt/conda/bin/conda install curl conda-verify conda-build mkl-include cmake -c anaconda &&  \
    /opt/conda/bin/conda install make cmake git graphviz gperftools git-lfs docopt -c conda-forge && \
    /opt/conda/bin/conda clean -afy
RUN pip --no-cache-dir install contexttimer future transformers==3.0.2 docopt

RUN pip --no-cache-dir install onnxruntime==1.4.0

# Install c++ compiler only
RUN apt-get update && apt-get install -y g++ && rm -rf /var/lib/apt/lists/*
# OnnxRuntime needs libpython*.so
# see issue https://github.com/microsoft/onnxruntime/issues/2058
ENV LD_LIBRARY_PATH /opt/conda/lib

# build turbo
RUN mkdir -p /src && cd /src && git clone https://github.com/Tencent/TurboTransformers.git --recursive && cd ./TurboTransformers && \
    sh ./tools/build_and_run_unittests.sh $PWD -DWITH_GPU=OFF
