FROM IMAGE_BASE

RUN apt-get update && \
    apt-get install -y curl git wget bzip2 build-essential ninja-build g++ && rm -rf /var/lib/apt/lists/*

ENV PATH=/opt/miniconda3/bin:${PATH} CONDA_PREFIX=/opt/miniconda3
RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -p /opt/miniconda3 -b && \
    rm Miniconda3-latest-Linux-x86_64.sh && \
    conda update -y conda && \
    conda install pytorch=PYTORCH_VERSION torchvision==0.3.0 cudatoolkit=CUDA_VERSION -c pytorch && \
    conda install curl conda-verify conda-build mkl-include cmake -c anaconda && \
    conda install git git-lfs docopt -c conda-forge  && \
    conda clean -afy

RUN pip --no-cache-dir install contexttimer future transformers docopt
WORKDIR /workspace
