# Build ONNX Runtime for benchmark
#FROM continuumio/anaconda3:2020.07
FROM continuumio/miniconda3:4.8.3

RUN apt-get --allow-releaseinfo-change update && apt-get install -y gfortran build-essential
#RUN /opt/conda/bin/conda install cmake curl git numpy -c anaconda

# Change conda channels when you need
RUN 	echo "channels:" > ~/.condarc && \
	echo " - https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/" >> ~/.condarc && \
	echo " - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/" >> ~/.condarc && \
	echo " - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/" >> ~/.condarc && \
	echo " - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/" >> ~/.condarc && \
	echo " - defaults" >> ~/.condarc && \
	echo "ssl_verify: true" >> ~/.condarc && \
 	/opt/conda/bin/conda clean -i && \
	/opt/conda/bin/conda config --set allow_conda_downgrades true && \
  	/opt/conda/bin/conda info


# Try to install deps by anaconda
# NOTE:  1. MKL is installed with pytorch.
#           turbo-transformers will use the same MKL from pytorch

COPY ./docker/conda_environment_dev.cpu.yml .

RUN /opt/conda/bin/conda env update -n base -f conda_environment_dev.cpu.yml && \
    /opt/conda/bin/conda clean -afy

# Install c++ compiler only
RUN apt-get update && apt-get install -y g++ && rm -rf /var/lib/apt/lists/*
# OnnxRuntime needs libpython*.so
# see issue https://github.com/microsoft/onnxruntime/issues/2058
ENV LD_LIBRARY_PATH /opt/conda/lib

# build turbo
RUN mkdir -p /src && cd /src && git clone https://github.com/Tencent/TurboTransformers.git --recursive && cd ./TurboTransformers && \
    sh ./tools/build_and_run_unittests.sh $PWD -DWITH_GPU=OFF
